"""Add missing user relation with tasks

Revision ID: 23c3ed7ebb76
Revises: 597e84142709
Create Date: 2024-12-18 10:03:41.948026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c3ed7ebb76'
down_revision: Union[str, None] = '597e84142709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
